In [ ]:
import pandas as pd

In [ ]:
df=pd.read_csv('/content/earthquake_1995-2023.csv')
df.head()

,title,magnitude,date_time,cdi,mmi,alert,tsunami,sig,net,nst,dmin,gap,magType,depth,latitude,longitude,location,continent,country
0,"M 6.5 - 42 km W of Sola, Vanuatu",6.5,16/08/2023 12:47,7,4,green,0,657,us,114,7.177000,25.0,mww,192.955,-13.8814,167.1580,"Sola, Vanuatu",NaN,Vanuatu
1,"M 6.5 - 43 km S of Intipucá, El Salvador",6.5,19/07/2023 00:22,8,6,yellow,0,775,us,92,0.679000,40.0,mww,69.727,12.8140,-88.1265,"Intipucá, El Salvador",NaN,NaN
2,"M 6.6 - 25 km ESE of Loncopué, Argentina",6.6,17/07/2023 03:05,7,5,green,0,899,us,70,1.634000,28.0,mww,171.371,-38.1911,-70.3731,"Loncopué, Argentina",South America,Argentina
3,"M 7.2 - 98 km S of Sand Point, Alaska",7.2,16/07/2023 06:48,6,6,green,1,860,us,173,0.907000,36.0,mww,32.571,54.3844,-160.6990,"Sand Point, Alaska",NaN,NaN
4,M 7.3 - Alaska Peninsula,7.3,16/07/2023 06:48,0,5,NaN,1,820,at,79,0.879451,172.8,Mi,21.000,54.4900,-160.7960,Alaska Peninsula,NaN,NaN

In [ ]:
df.tail()

,title,magnitude,date_time,cdi,mmi,alert,tsunami,sig,net,nst,dmin,gap,magType,depth,latitude,longitude,location,continent,country
995,"M 7.1 - 85 km S of Tungor, Russia",7.1,27/05/1995 13:03,0,9,NaN,0,776,us,0,0.0,0.0,mwb,11.0,52.629,142.827,"Tungor, Russia",Asia,Russia
996,"M 7.7 - 249 km E of Vao, New Caledonia",7.7,16/05/1995 20:12,0,4,NaN,0,912,us,0,0.0,0.0,mw,20.2,-23.008,169.900,"Vao, New Caledonia",NaN,NaN
997,"M 6.9 - 27 km NNW of Maubara, Timor Leste",6.9,14/05/1995 11:33,0,6,NaN,0,732,us,0,0.0,0.0,mw,11.2,-8.378,125.127,"Maubara, Timor Leste",NaN,Indonesia
998,"M 6.6 - 10 km W of Aianí, Greece",6.6,13/05/1995 08:47,0,9,NaN,0,670,us,0,0.0,0.0,mw,14.0,40.149,21.695,"Aianí, Greece",Europe,Greece
999,"M 7.1 - 14 km NE of Cabatuan, Philippines",7.1,05/05/1995 03:53,0,7,NaN,0,776,us,0,0.0,0.0,mw,16.0,12.626,125.297,"Cabatuan, Philippines",NaN,Philippines

In [ ]:
df.shape

(1000, 19)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 19 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   title      1000 non-null   object
 1   magnitude  1000 non-null   float64
 2   date_time  1000 non-null   object
 3   cdi        1000 non-null   int64
 4   mmi        1000 non-null   int64
 5   alert      449 non-null    object
 6   tsunami    1000 non-null   int64
 7   sig        1000 non-null   int64
 8   net        1000 non-null   object
 9   nst        1000 non-null   int64
 10  dmin       1000 non-null   float64
 11  gap        1000 non-null   float64
 12  magType    1000 non-null   object
 13  depth      1000 non-null   float64
 14  latitude   1000 non-null   float64
 15  longitude  1000 non-null   float64
 16  location   994 non-null    object
 17  continent  284 non-null    object
 18  country    651 non-null    object
dtypes: float64(6), int64(5), object(8)
memory usage: 148.6+ KB

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
dupe_mask=df.duplicated(subset=["title","date_time"],keep=False)
print("Rows involed in a title+date_time duplicate:",dupe_mask.sum())
df[dupe_mask].sort_values("title")[["title","date_time","magnitude","country"]]

Rows involed in a title+date_time duplicate: 4

                                   title         date_time  magnitude country
67  M 6.5 - 71 km SE of Nikolski, Alaska  11/01/2022 12:39        6.5     NaN
68  M 6.5 - 71 km SE of Nikolski, Alaska  11/01/2022 12:39        6.5     NaN
70  M 6.7 - 91 km SE of Nikolski, Alaska  11/01/2022 11:35        6.7     NaN
71  M 6.7 - 91 km SE of Nikolski, Alaska  11/01/2022 11:35        6.7     NaN

In [ ]:
df.drop_duplicates(subset=["title","date_time"],inplace=True)

In [ ]:
df.loc[66:71,["title","date_time"]]

                                    title         date_time
66  M 6.6 - 80 km SW of Labuan, Indonesia  14/01/2022 09:05
67   M 6.5 - 71 km SE of Nikolski, Alaska  11/01/2022 12:39
69   M 6.6 - 53 km SE of Nikolski, Alaska  11/01/2022 12:39
70   M 6.7 - 91 km SE of Nikolski, Alaska  11/01/2022 11:35

In [ ]:
missing

title          0
magnitude      0
date_time      0
cdi            0
mmi            0
alert        549
tsunami        0
sig            0
net            0
nst            0
dmin           0
gap            0
magType        0
depth          0
latitude       0
longitude      0
location       6
continent    714
country      347
dtype: int64